# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b76d6c4b2751846c8ed03689b24bf1cf2f6b9b897c8b84811d183a0beeac35af17da47d8da1139788f764d684047d82bce9ab422a21e768ffe7b5aec55cb767

test:
  secret_key_base: 1039f74f29c3afd8583ee67f577f0ed59a4da50c7810ad3b2fc0aac85ff889283e153098fb2e41900411fd555204ef55fa90558619670bf42f3b7120980f4c1c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
